import type { BoardDefinition } from "./types.js";

export const boardCatalog: BoardDefinition[] = [
  {
    type: "arduino-uno",
    name: "Arduino Uno",
    family: "arduino",
    description: "Standard ATmega328P board with digital, analog, PWM, and power headers.",
    defaultFileExtension: "ino",
    codeLanguage: "arduino",
    fqbn: "arduino:avr:uno",
    supportedComponentTypes: [
      "led",
      "push-button",
      "resistor",
      "buzzer",
      "potentiometer",
      "servo-motor",
      "ultrasonic-sensor",
      "breadboard",
      "jumper-wire",
      "power-5v",
      "ground",
    ],
    pinCapabilities: {
      D0: { digital: true, serial: true },
      D1: { digital: true, serial: true },
      D2: { digital: true },
      D3: { digital: true, pwm: true },
      D4: { digital: true },
      D5: { digital: true, pwm: true },
      D6: { digital: true, pwm: true },
      D7: { digital: true },
      D8: { digital: true },
      D9: { digital: true, pwm: true },
      D10: { digital: true, pwm: true },
      D11: { digital: true, pwm: true },
      D12: { digital: true },
      D13: { digital: true },
      A0: { analog: true, digital: true },
      A1: { analog: true, digital: true },
      A2: { analog: true, digital: true },
      A3: { analog: true, digital: true },
      A4: { analog: true, digital: true },
      A5: { analog: true, digital: true },
    },
  },
  {
    type: "arduino-nano",
    name: "Arduino Nano",
    family: "arduino",
    description: "Compact ATmega328P board suitable for breadboard projects.",
    defaultFileExtension: "ino",
    codeLanguage: "arduino",
    fqbn: "arduino:avr:nano",
    supportedComponentTypes: [
      "led",
      "push-button",
      "resistor",
      "buzzer",
      "potentiometer",
      "servo-motor",
      "ultrasonic-sensor",
      "breadboard",
      "jumper-wire",
      "power-5v",
      "ground",
    ],
    pinCapabilities: {
      D2: { digital: true },
      D3: { digital: true, pwm: true },
      D4: { digital: true },
      D5: { digital: true, pwm: true },
      D6: { digital: true, pwm: true },
      D7: { digital: true },
      D8: { digital: true },
      D9: { digital: true, pwm: true },
      A0: { analog: true, digital: true },
      A1: { analog: true, digital: true },
      A2: { analog: true, digital: true },
      A3: { analog: true, digital: true },
      A4: { analog: true, digital: true },
      A5: { analog: true, digital: true },
    },
  },
];

export const boardByType = Object.fromEntries(boardCatalog.map((board) => [board.type, board]));
