import type { BoardDefinition } from "./types.js";

export const boardCatalog: BoardDefinition[] = [
  {
    type: "arduino-uno",
    name: "Arduino Uno",
    family: "arduino",
    description: "Standard ATmega328P board with digital, analog, PWM, and power headers.",
    defaultFileExtension: "ino",
    codeLanguage: "arduino",
    fqbn: "arduino:avr:uno",
    supportedComponentTypes: [
      "led",
      "push-button",
      "resistor",
      "buzzer",
      "potentiometer",
      "servo-motor",
      "ultrasonic-sensor",
      "breadboard",
      "jumper-wire",
      "power-5v",
      "ground",
    ],
    pinCapabilities: {
      D0: { digital: true, serial: true },
      D1: { digital: true, serial: true },
      D2: { digital: true },
      D3: { digital: true, pwm: true },
      D4: { digital: true },
      D5: { digital: true, pwm: true },
      D6: { digital: true, pwm: true },
      D7: { digital: true },
      D8: { digital: true },
      D9: { digital: true, pwm: true },
      D10: { digital: true, pwm: true },
      D11: { digital: true, pwm: true },
      D12: { digital: true },
      D13: { digital: true },
      A0: { analog: true, digital: true },
      A1: { analog: true, digital: true },
      A2: { analog: true, digital: true },
      A3: { analog: true, digital: true },
      A4: { analog: true, digital: true },
      A5: { analog: true, digital: true },
    },
  },
  {
    type: "arduino-nano",
    name: "Arduino Nano",
    family: "arduino",
    description: "Compact ATmega328P board suitable for breadboard projects.",
    defaultFileExtension: "ino",
    codeLanguage: "arduino",
    fqbn: "arduino:avr:nano",
    supportedComponentTypes: [
      "led",
      "push-button",
      "resistor",
      "buzzer",
      "potentiometer",
      "servo-motor",
      "ultrasonic-sensor",
      "breadboard",
      "jumper-wire",
      "power-5v",
      "ground",
    ],
    pinCapabilities: {
      D2: { digital: true },
      D3: { digital: true, pwm: true },
      D4: { digital: true },
      D5: { digital: true, pwm: true },
      D6: { digital: true, pwm: true },
      D7: { digital: true },
      D8: { digital: true },
      D9: { digital: true, pwm: true },
      A0: { analog: true, digital: true },
      A1: { analog: true, digital: true },
      A2: { analog: true, digital: true },
      A3: { analog: true, digital: true },
      A4: { analog: true, digital: true },
      A5: { analog: true, digital: true },
    },
  },
  {
    type: "esp32-devkit-v1",
    name: "ESP32 DevKit V1",
    family: "esp",
    description: "Wi-Fi and Bluetooth microcontroller board with mixed digital, PWM, ADC, and serial pins.",
    defaultFileExtension: "ino",
    codeLanguage: "arduino",
    fqbn: "esp32:esp32:esp32",
    supportedComponentTypes: [
      "led",
      "push-button",
      "resistor",
      "buzzer",
      "potentiometer",
      "servo-motor",
      "ultrasonic-sensor",
      "breadboard",
      "jumper-wire",
      "power-5v",
      "ground",
    ],
    pinCapabilities: {
      D2: { digital: true },
      D4: { digital: true },
      D5: { digital: true },
      D12: { digital: true },
      D13: { digital: true },
      D14: { digital: true },
      D15: { digital: true },
      D18: { digital: true },
      D19: { digital: true },
      D21: { digital: true },
      D22: { digital: true },
      D23: { digital: true },
      D25: { digital: true, analog: true },
      D26: { digital: true, analog: true },
      D27: { digital: true, analog: true },
      D32: { digital: true, analog: true },
      D33: { digital: true, analog: true },
      D34: { analog: true },
      D35: { analog: true },
    },
  },
  {
    type: "esp8266-nodemcu",
    name: "ESP8266 NodeMCU",
    family: "esp",
    description: "Compact Wi-Fi board with digital GPIO and a single analog input.",
    defaultFileExtension: "ino",
    codeLanguage: "arduino",
    fqbn: "esp8266:esp8266:nodemcuv2",
    supportedComponentTypes: [
      "led",
      "push-button",
      "resistor",
      "buzzer",
      "potentiometer",
      "servo-motor",
      "ultrasonic-sensor",
      "breadboard",
      "jumper-wire",
      "power-5v",
      "ground",
    ],
    pinCapabilities: {
      D0: { digital: true },
      D1: { digital: true },
      D2: { digital: true },
      D3: { digital: true },
      D4: { digital: true },
      D5: { digital: true },
      D6: { digital: true },
      D7: { digital: true },
      D8: { digital: true },
      A0: { analog: true },
    },
  },
  {
    type: "raspberry-pi-pico",
    name: "Raspberry Pi Pico",
    family: "raspberry-pi",
    description: "RP2040 development board with digital GPIO, PWM, ADC, and serial support.",
    defaultFileExtension: "ino",
    codeLanguage: "arduino",
    fqbn: "rp2040:rp2040:rpipico",
    supportedComponentTypes: [
      "led",
      "push-button",
      "resistor",
      "buzzer",
      "potentiometer",
      "servo-motor",
      "ultrasonic-sensor",
      "breadboard",
      "jumper-wire",
      "power-5v",
      "ground",
    ],
    pinCapabilities: {
      GP0: { digital: true, serial: true },
      GP1: { digital: true, serial: true },
      GP2: { digital: true, pwm: true },
      GP3: { digital: true, pwm: true },
      GP4: { digital: true, pwm: true },
      GP5: { digital: true, pwm: true },
      GP6: { digital: true, pwm: true },
      GP7: { digital: true, pwm: true },
      GP8: { digital: true, pwm: true },
      GP9: { digital: true, pwm: true },
      GP10: { digital: true, pwm: true },
      GP11: { digital: true, pwm: true },
      GP26: { analog: true, digital: true },
      GP27: { analog: true, digital: true },
      GP28: { analog: true, digital: true },
    },
  },
];

export const boardByType = Object.fromEntries(boardCatalog.map((board) => [board.type, board]));
